[deps]
bottleneck = ">=1.3"
cartopy = ">=0.22"
configobj = ">=5.0"
dask = ">=2024.3"
gdal = ">=3.8"
geopandas = ">=0.14"
ipython = ">=8.22"
jupyter = ">=1.0"
jupyterlab = ">=4.1"
matplotlib = ">=3.8"
motionless = ">=1.3"
netcdf4 = ">=1.6"
numpy = "<2.0"
numpydoc = ">=1.6"
pandas = ">=2.2"
pip = ">=24.0"
pyproj = ">=3.6"
pytables = ">=3.9"
pytest = ">=8.1"
python = ">=3.12"
rioxarray = ">=0.15"
salem = ">=0.3"
scikit-image = ">=0.22"
scikit-learn = ">=1.4"
scipy = ">=1.12"
seaborn = ">=0.13"
shapely = ">=2.0"
xarray = ">=2024.2"

[pip.deps]
oggm = "@ git+https://github.com/OGGM/oggm.git@9d173038862f36a21838034da07243bd189ef2d0"
certifi = ""
progressbar2 = ">=4.4"
joblib = ">=1.3"
MBSandbox = "@Â git+https://github.com/OGGM/massbalance-sandbox"

[extras]
channels = ["conda-forge"]
