[deps]
bottleneck = ""
ipython = ""
netcdf4 = ""
pyproj = ""
matplotlib = ""
pytables = ""
numpydoc = ""
pip = ""
scikit-learn = ""
configobj = ""
seaborn = ""
jupyterlab = ""
rioxarray = ""
pandas = ""
dask = ""
gdal = ""
xarray = ""
jupyter = ""
python = "3.10"
salem = ""
cartopy = ""
geopandas = ""
typeguard = ""
pytest = ""
shapely = ""
motionless = ""
numpy = ""
scipy = ""
scikit-image = ""

[pip.deps]
oggm = ""
certifi = ""
progressbar2 = ""
joblib = ""
MBSandbox = "@Â git+https://github.com/OGGM/massbalance-sandbox"

[extras]
channels = ["conda-forge"]
